name: CI


on:
  push:
    branches: ["main"]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:

      - name: Chechout SCM
        uses: actions/checkout@v4 

      - name: Setup puthon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install pytest     
        run: pip install pytest flask-testing

      - name: run unit test
        run: paytest  

          