name: CI


on:
  push:
    branches: ["main"]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:

      - name: Chechout SCM
        uses: actions/checkout@v4 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     